export const chartData = [
  { name: "" },
  { name: "Sprint 1", uv: 7 },
  { name: "Sprint 2", uv: 11 },
  { name: "Sprint 3", uv: 10 },
  { name: "Sprint 4", uv: 14 },
  { name: "" },
  { name: "" },
];

export const header = [
  "Type",
  "Key",
  "Summary",
  "Status",
  "Epic",
  "Version",
  "Points",
  "Sprint",
];
export const tableData = [
  {
    Type: "Feature",
    Key: "TOWEB-3156",
    Summary: "Search Page Edit state",
    Status: "In UX Review",
    Epic: "Search Page New UI Update",
    Version: "2022.1.0.WTO",
    Points: 5,
    Sprint: "Sprint 84",
  },
  {
    Type: "BugFix",
    Key: "TOWEB-3157",
    Summary: "Search Page keyword UI issue",
    Status: "Ready For Development",
    Epic: "",
    Version: "2022.3.0.WTO",
    Sprint: "Sprint 85",
  },
  {
    Type: "Feature",
    Key: "TOWEB-3158",
    Summary: "Search Page Search Tag",
    Status: "Ready For Development",
    Epic: "Search Page New UI Update",
    Version: "2022.3.0.WTO",
    Points: 5,
    Sprint: "Sprint 85",
  },
  {
    Type: "Feature",
    Key: "TOWEB-3159",
    Summary: "Search Page Search Area Toggle",
    Status: "In PO Review",
    Epic: "Search Page New UI Update",
    Version: "2022.1.0.WTO",
    Points: 8,
    Sprint: "Sprint 84",
  },
  {
    Type: "BugFix",
    Key: "TOWEB-3156",
    Summary: "Search Page ProjectLeads 500 error",
    Status: "In Development",
    Epic: "",
    Version: "2022.2.0.WTO",
    Sprint: "Sprint 84",
  },
];
